language: ruby
rvm:
  - 2.6.6
before_install: gem install bundler -v 2.2.5
before_script:
  - cp config/config.travis.yml config/config.yml
services:
  - rabbitmq
script:
  - bundle exec rspec
addons:
  code_climate:
      repo_token: 2fb5666778862e3d7db94953485defc99c41433f787b43d9ec7dd06220423d37
